### ISSUE TITLE
Can you do a wan version of this extension?

### ISSUE THREAD

**Issue by L1ghtn1ng** [Josholith/gnome-extension-lan-ip-address#1]
Title says it all.

**Comment by Josholith** [comment]
Thanks for your issue. Are you looking for a simple extension like this one (no frills) that just shows your public IP address?

**Comment by L1ghtn1ng** [comment]
Yes or you could tag it on to this extension which you could view either by clicking on your Lan IP to then show public address or extension option to show it like with Lan IP. Something simple like that if you are open to incorporating it into the existing extension?
________________________________

**Comment by Josholith** [comment]
No plans to add WAN IP at this time. This extension by design only shows your internal LAN IP address, just as the name suggests. It is designed for developers and other engineers who only need to see their LAN address in a convenient place, and with total privacy (no calls to the Internet).

There are many other good extensions available that can show your WAN (public) IP address. You might check out "All IP Addresses" extension at https://extensions.gnome.org/extension/3994/all-ip-addresses/ , which was based on a fork of this extension, and allows the user to toggle display of LAN IPv4 address, LAN IPv6 address, and WAN (public) address. It should be noted that the "All IP Addresses" extension determines the WAN address by making a DNS request to Google DNS. In contrast, my extension sends absolutely zero requests or packets to the Internet.
