### ISSUE TITLE
gnome 41 

### ISSUE THREAD

**Issue by backl1n** [Josholith/gnome-extension-lan-ip-address#13]
probleme with extension after update to gnome 41 :  i look my IP vpn with extension
Object 0xe0070524988 is not a subclass of GObject_Object, it's a Object

**Comment by Josholith** [comment]
I got this when doing testing on GNOME 42.  I don't remember getting this on GNOME 41, but will do some additional testing.  I will be adding support for GNOME 42 within the next week, which will include the fix for this exact error, so it should fix this for anyone getting the same error on GNOME 41.  Stay tuned!
